'use strict';

require.config({
	paths: {
		jquery: 'node_modules/jquery/dist/jquery.min',
		async:'node_modules/requirejs-async/async',
		lodash: 'node_modules/lodash/lodash.min',
		moment: 'node_modules/moment/min/moment.min',
		slimscroll: 'node_modules/jquery-slimscroll/jquery.slimscroll.min',
		blockui: 'node_modules/block-ui/jquery.blockUI',
		'popover': 'node_modules/jquery-popover/dist/jquery-popover-0.0.3',
		bootstrap: 'src/bootstrap',
		'bootstrap.hover.dropdown': 'node_modules/bootstrap-hover-dropdown/bootstrap-hover-dropdown',
		framework: 'src/vendor/framework',
		uiBootstrap: 'src/vendor/ui.bootstrap',
		quickSideBar: 'src/vendor/quick-sidebar',
		text: 'node_modules/requirejs-text/text',
		angular: 'node_modules/angular/angular.min',
		angularRoute: 'node_modules/angular-route/angular-route.min',
		angularCookies: 'node_modules/angular-cookies/angular-cookies.min',
		angularResource: 'node_modules/angular-resource/angular-resource.min',
		angularUIRouter: 'node_modules/@uirouter/angularjs/release/angular-ui-router.min',
		angularAnimate: 'node_modules/angular-animate/angular-animate.min',
		angularAria: 'node_modules/angular-aria/angular-aria.min',
		angularMessages: 'node_modules/angular-messages/angular-messages.min',
		angularMaterial: 'node_modules/angular-material/angular-material.min',
		angularValidation: 'node_modules/angular-validation/dist/angular-validation.min',
		angularValidationRule: 'src/vendor/angular-validation-rule',
		angularSanitize: 'node_modules/angular-sanitize/angular-sanitize.min',
		angularMoment: 'node_modules/angular-moment/angular-moment.min',
		interact: 'node_modules/interact.js/dist/interact.min',
		angularCalendar: 'node_modules/angular-bootstrap-calendar/dist/js/angular-bootstrap-calendar-tpls.min',

		uiSelect: 'node_modules/ui-select/dist/select.min',
		ngTagsInput: 'node_modules/ng-tags-input/build/ng-tags-input.min',
		angularGrowl: 'src/vendor/angular-growl',
		timePicker: 'src/vendor/bootstrap-datetimepicker',
		ngSortable: 'node_modules/ng-sortable/dist/ng-sortable.min',
		dndLists: 'node_modules/angular-drag-and-drop-lists/angular-drag-and-drop-lists.min',
		angularFileUpload : 'node_modules/angular-file-upload/dist/angular-file-upload.min',
		three : 'node_modules/three/build/three.min',
        clipboard: 'src/vendor/clipboard'
	},
	shim: {
		'slimscroll': ['jquery'],
		'popover': ['jquery'],
		'bootstrap.hover.dropdown': ['jquery', 'angular'],
		'angular': {deps: ['jquery'], 'exports' : 'angular'},
		'angularCookies': ['angular'],
		'angularRoute': ['angular'],
		'angularResource': ['angular'],
		'angularUIRouter': ['angular'],
		'angularAnimate': ['angular'],
		'angularAria': ['angular'],
		'angularMessages': ['angular'],
		'angularMaterial': ['angularAnimate', 'angularAria', 'angularMessages'],
		'angularValidation': ['angular'],
		'angularValidationRule': ['angularValidation'],
		'angularSanitize': ['angular'],
		'angularMoment': ['angular', 'moment'],
		'angularCalendar': ['angular', 'moment', 'interact'],
		'uiSelect': ['angularSanitize'],
		'uiBootstrap': ['angular', 'angularAnimate'],
		'ngTagsInput': ['angular'],
		'ngSortable': ['angular'],
		'dndLists': ['angular'],
		'angularGrowl': ['angular'],
		'angularFileUpload': ['angular']
	},
	priority: [
		"angular"
	],
	deps: ['bootstrap'],
	waitSeconds: 30,
	baseUrl: '/',
});